// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oaiygtecjjepjuebfeai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9haXlndGVjamplcGp1ZWJmZWFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MzI2NzksImV4cCI6MjA2MjQwODY3OX0.uRXx1L6THPziMWkmusY9zkdMnzBJWrP4ay4NCHVQ_Ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);